myeda/eda/urls.py
from django.urls import path
from . import views

app_name = 'eda'
urlpatterns = [
    path('', views.load_eda, name="eda"),
    path('profile/', views.profile, name="profile"),
    path('letter/', views.letter, name="letter"),
    path('test/', views.ready_eda, name="ready"),
]

myeda/myeda/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('eda/', include('eda.urls')),
    path('admin/', admin.site.urls, name="admin"),
]

myeda/eda/models.py
from django.db import models

## DataFrame 속성
# id (pk)
# name
# kind
# html
# 


## Plot 속성

# Create your models here.
class Dataframe(models.Model):
    def __str__(self):
        return "%s DataFrame" % self.name
    # id (pk)
    name = models.CharField(max_length=40, null=False, unique=True)
    _html = models.TextField()


class Graph_plot(models.Model):
    def __str__(self):
        return "%s-%s (hue=%s) Plot" % (self.x, self.y, self.hue)

    # id (pk)
    name = models.CharField(max_length=60, null=False, unique=True)
    x = models.CharField(default="", max_length=30)
    y = models.CharField(default="", max_length=30)
    hue = models.CharField(max_length=30, null=True)
    _html = models.TextField()


class Visitor(models.Model):
    def __str__(self):
        return self.name

    # id (pk)
    name = models.CharField(default="", max_length=60)
    content = models.CharField(default="", max_length=500)

myeda/eda/views.py
from django.shortcuts import render
from django.http import HttpResponse
import json
from .service import *

# bootstrap 적용한 html Test 용
def load_eda(request):
    print("load_eda 호출됨")
    if request.method == "POST":
        print("load_eda POST 요청됨")
        try:
            num = request.POST.get('num', None)
            # 구현
            if num == '2':
                html_context = overall_analysis()
                
            elif num == '3':
                html_context = data_relation_1()

            elif num == '4':
                html_context = data_relation_2()

            elif num == '5':
                html_context = data_relation_3()
            elif num == '6':
                html_context = verificate()
            else:
                raise Exception("불러올 페이지가 없습니다.")
        except Exception as e:
            raise KeyError

        # print(html_context)        

        context = {'html':html_context} # 구현

        return HttpResponse(json.dumps(context), content_type="application/json")

    head, tail = head_and_tail()
    context = {'head':head, 'tail':tail}

    return render(request, 'index.html', context)


def profile(request):
    context = {}
    return render(request, 'introduce.html', context)

def letter(request):
    try:
        if request.method == "POST":
            print("letter POST 요청됨")
            
            ## 메시지 DB에 저장
            name = request.POST.get("name")
            content = request.POST.get("content")
            save_letter(name, content)
            ##

            alert("전송 완료되었습니다.")
            
        else:
            alert("올바른 요청이 아닙니다.")

    except:
        alert("예기치 못한 오류가 발생하였습니다.")
    finally:
        return render(request, 'index.html', {})
        
    return render(request, 'index.html', {})
    


def ready_eda(request):
    context = {}
    return render(request, 'bootstrap_test.html', context)

myeda/eda/templates/eda/bootstrap_test.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 위 3개의 메타 태그는 *반드시* head 태그의 처음에 와야합니다; 어떤 다른 콘텐츠들은 반드시 이 태그들 *다음에* 와야 합니다 -->
    <title>부트스트랩 101 템플릿</title>

    <!-- 부트스트랩 -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- IE8 에서 HTML5 요소와 미디어 쿼리를 위한 HTML5 shim 와 Respond.js -->
    <!-- WARNING: Respond.js 는 당신이 file:// 을 통해 페이지를 볼 때는 동작하지 않습니다. -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <h1>Hello, world!</h1>
    <!--  이 템플릿을 사용하고 싶다  -->
    <!--    http://bootstrapk.com/examples/dashboard/-->
    <!-- jQuery (부트스트랩의 자바스크립트 플러그인을 위해 필요합니다) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!-- 모든 컴파일된 플러그인을 포함합니다 (아래), 원하지 않는다면 필요한 각각의 파일을 포함하세요 -->
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>

myeda/eda/templates/eda/index.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>My EDA Project</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/simple-sidebar.css' %}" rel="stylesheet">

  <!-- favicon -->
  <link href="{% static 'free-bar-chart-icon-676-thumb.png' %}" rel="shorcut icon">

  <!-- Jquery -->
  <script src="//code.jquery.com/jquery-3.3.1.min.js"></script>

  <!-- Font_Awesome -->
  <script src="https://kit.fontawesome.com/5f3e222d81.js" crossorigin="anonymous"></script>

  <style>
    .back-to-top {
      cursor: pointer;
      position: fixed;
      bottom: 20px;
      right: 20px;
      display:none;
      color: #fff;
      background-color: lightgray;
      border-color: lightgray;
    }
  </style>

</head>

<body>

  <div class="d-flex" id="wrapper">

    <!-- Sidebar -->
    <div class="bg-light border-right" id="sidebar-wrapper">
      <div class="sidebar-heading">US Health Insurance Dataset Analysis</div>
      <div class="list-group list-group-flush">
        <a href="" class="list-group-item list-group-item-action bg-light" name="1" style="background-color: #dae0e5!important;">Data Set에 대한 설명</a>
        <a href="#" class="list-group-item list-group-item-action bg-light" id="list-group-item" name="2">전반적인 데이터 분석</a>
        <a href="#" class="list-group-item list-group-item-action bg-light" id="list-group-item" name="3">데이터 상관관계 분석 Ⅰ</a>
        <a href="#" class="list-group-item list-group-item-action bg-light" id="list-group-item" name="4">데이터 상관관계 분석 Ⅱ</a>
        <a href="#" class="list-group-item list-group-item-action bg-light" id="list-group-item" name="5">데이터 상관관계 분석 Ⅲ</a>
        <a href="#" class="list-group-item list-group-item-action bg-light" id="list-group-item" name="6">데이터 검증</a>
        <a href="#" class="list-group-item list-group-item-action bg-light" id="list-group-item" name="7">(준비 중) DIY Graph !</a>
      </div>
    </div>
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper">

      <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
        <button class="btn btn-primary" id="menu-toggle">Hide</button>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
            <li class="nav-item active">
              <a class="nav-link" href="">홈 <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://github.com/Ting-Kim"><i class="fab fa-github"></i></a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                더보기
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <!-- <a class="dropdown-item" href="#">관리자에게 한마디</a> -->
                <!-- Button trigger modal -->
                <!-- <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
                  Launch demo modal
                </button> -->
                <a href="#myModal" class="dropdown-item" data-toggle="modal" data-target="#myModal">
                  관리자에게 한마디
                </a>
                <a class="dropdown-item" href="{% url 'eda:profile' %}">관리자 프로필</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="https://programmers.co.kr/"><img src="{% static 'eda/programmers_logo.png' %}" style="width:80%; height: 80%"></a>
              </div>
            </li>
          </ul>
        </div>
      </nav>

      <!--  EDA Results 넣을 곳   -->
      {% autoescape off %}
      <div class="container-fluid">
        <h1 class="mt-4">US Health Insurance Dataset</h1>
        <p>Data Set에 대한 소개는 <a href="https://www.kaggle.com/teertha/ushealthinsurancedataset">여기</a>를 참조해주세요.</p>
        <hr>
        <h4>Data Set 선정 이유</h4>
        <hr>
        <ul>
          <li>다룰 수 있는 데이터 타입</li>
          <li>유추할 수 있는 맥락</li>
          <li>추천 시스템</li>
        </ul>
        <p>본 데이터셋을 선정한 이유는 크게 3가지입니다.
          데이터를 다룬 경험이 많지 않기에 실습에서 다룰 수 있는 데이터 타입을 가진 데이터셋을 선정해야 했습니다.
          또한, 데이터 분석의 결론을 내는 것을 중요하다고 생각하여, 데이터 속성의 종류가 너무 많은 경우 제외하였습니다.
        </p>
        <p>
          데이터 속성 간 관계를 유추할 수 있는 데이터셋을 선정하였습니다. 데이터에 대한 배경지식이 있을 경우,
          신뢰성 있는 가설을 세우는 등 전반적인 데이터 분석에 많은 도움이 되기 때문입니다.
        </p>
        <p>
          추후 AI 기반 추천 시스템을 구현하고 싶은 생각을 가지고 있습니다.
          추천 시스템과 관련해서 쉽게 생각할 수 있는 주제가 보험, 금융, 광고 등인데,
          데이터 분석이 보험에 가장 큰 효력을 발휘할 것 같다고 생각했습니다.
        </p>
        <br>
        <hr>
        <br>
        <h4>데이터 변수 종류</h4>
        <div>
          <table class="table">
            <thead>
              <th scope="col">#</th>
              <th scope="col">변수명</th>
              <th scope="col">설명</th>
            </thead>
            <tbody>
              <tr>
                <th scope="row">1</th>
                <td>age</td>
                <td><code>&#60;type:int&#62;</code>, 표본의 나이</td>
              </tr>
              <tr>
                <th scope="row">2</th>
                <td>sex</td>
                <td><code>&#60;type:object&#62;</code>, 표본의 성별 ( <em>'male' / 'female'</em> )</td>
              </tr>
              <tr>
                <th scope="row">3</th>
                <td>bmi</td>
                <td><code>&#60;type:float&#62;</code>, 표본의 <a href="https://namu.wiki/w/BMI">bmi</a> 수치</td>
              </tr>
              <tr>
                <th scope="row">4</th>
                <td>children</td>
                <td><code>&#60;type:int&#62;</code>, 건강 보험이 적용되는 자녀 및 부양 가족 수</td>
              </tr>
              <tr>
                <th scope="row">5</th>
                <td>smoker</td>
                <td><code>&#60;type:object&#62;</code>, 흡연 여부 ( <em>'yes' / 'no'</em> )</td>
              </tr>
              <tr>
                <th scope="row">6</th>
                <td>region</td>
                <td><code>&#60;type:object&#62;</code>, 표본(보험 가입자)의 거주지</td>
              </tr>
              <tr>
                <th scope="row">7</th>
                <td>charges</td>
                <td><code>&#60;type:float&#62;</code>, 'Individual medical costs billed by health insurance.' 라고 설명되어 있는데, <br>
                  개인이 지불하는 건강 보험료 금액인지 부양 가족을 포함하여 1인당 납부하는 금액인지 모호하다.</td>
              </tr>
            </tbody>
          </table>
        </div>
        <div>
          <br>
          <!-- {% autoescape off %} -->
          <b>상단값 확인 (5)</b>
          {{ head }}
          <br>
          <b>하단값 확인 (5)</b>
          {{ tail }}
          <!-- {% endautoescape %} -->
          <br>
          <br>
          <h4>✏ 가설 세워보기</h4>

          <ul>
            <li><code>age, bmi</code>가 높고 (<code>smoker</code>=='yes')인 경우 <code>charges</code>가 높지 않을까?</li>
            <li>(<code>sex</code>=='male')인 경우가 <code>smoker</code>의 비중이 높지 않을까?</li>
            <li><code>children</code>이 많을수록 더 높은 <code>charges</code>를 가지지 않을까?</li>
          </ul>
          <br>
          <br>
          <br>
        </div>
      </div>
      <a id="back-to-top" href="#" class="btn btn-primary btn-lg back-to-top" role="button" title="Click to return on the top page" data-toggle="tooltip" data-placement="left">
        <span class="glyphicon glyphicon-chevron-up"><i class="far fa-caret-square-up"></i></span>
      </a>
      </div>
      <!-- /#container-fluid -->
      {% endautoescape %}
    <!-- /#page-content-wrapper -->

      <!--  EDA Results 넣을 곳   -->

  </div>
  <!-- /#wrapper -->

  <div class="modal fade" id="myModal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title">👨🏻‍💻 관리자에게 한마디</h4>
        </div>
        <div class="modal-body">
          <!-- <p>One fine body&hellip;</p> -->
          <form method="POST" action="{% url 'eda:letter' %}">{% csrf_token %}
            이름 : <br>
            <input type="text" name="name" maxlength="20"><br>
            내용 : <br>
            <textarea placeholder="자유롭게 작성해주세요" name="content" cols="60" rows="5"></textarea>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">닫기</button>
		<input type="submit" class="btn btn-primary" onclick="result()"></button>
              </div>
            </form>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->



  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Menu Toggle Script -->
  <script>
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });

    $(".list-group-item").on('click',function(e){
      var num = $(this).attr('name');
      if (num == 1){
        document.getElementsByName("1")[0].setAttribute('style', 'background-color:#dae0e5!important;')
        return
      }
      if (num == 7){
        alert("준비 중인 서비스입니다 :)")
        return
      }
      document.getElementsByName("1")[0].setAttribute('style', 'background-color:#f8f9fa!important;')
      e.preventDefault();
      console.log(num);
      console.log(this);
      $.ajax({
        url: "{% url 'eda:eda' %}",
        type:"POST",
        data:{"num":num, "csrfmiddlewaretoken":'{{ csrf_token }}'},
        dataType: "json",
        success: function(response){
          // alert("통신 Success!");
          $(".container-fluid").html(response['html']);
            
          },
        error: function(request, status, error){
          alert(error);
          document.body.innerHTML = "<b>code = " + request.status + "<br> message = </b>" + request.responseText;
        },
      })
    });

    $(document).ready(function(){
     $(window).scroll(function () {
        if ($(this).scrollTop() > 50) {
          $('#back-to-top').fadeIn();
        } else {
          $('#back-to-top').fadeOut();
        }
      });
        // scroll body to 0px on click
      $('#back-to-top').click(function () {
        $('#back-to-top').tooltip('hide');
        $('body,html').animate({
          scrollTop: 0
        }, 800);
          return false;
        });
        
      $('#back-to-top').tooltip('show');

    });

    // $('#myModal').modal({
    //   keyboard: false
    // })
    // $('#myModal').on('shown.bs.modal', function () {
    //   $('#myInput').focus()
    // })

    function result(){
      alert("전송이 완료되었습니다.");
    }

  </script>

</body>

</html>

myeda/eda/templates/eda/introduce.html
<html>
	<head>
		{% load static %}
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
		<title>자기소개</title>
		<link rel="stylesheet" type="text/css" href="{% static 'eda/css/style.css' %}">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
	</head>
<body>
	<article id="10b0fe6e-af8f-428f-9f55-c247f7924574" class="page sans">
		<header>
			<div class="page-header-icon undefined">
				<span class="title-icon">🙎🏻‍♂️</span>
			</div>
			<h1 class="page-title">Profile</h1>
		</header><div class="page-body">
			<div id="4da2e4c1-6cf2-4712-9517-585b6324a012" class="column-list">
				<div id="230b657c-c29d-4780-9b45-356539532497" style="width:31.25%" class="column">
					<figure id="427b0443-eaaa-4444-a834-871e85fe24c4" class="image">
						<img style="width:192px" src="{% static 'eda/selfie.jpg' %}"/>
					</figure>
					<hr>
					<p id="2fda5412-2d59-4594-8f9e-f98952705d7c" class="">
						<b>김태호(Taeho Kim)</b>
					</p>
					<p id="62b56183-68b4-4a21-b105-d18de7418ff5" class="">커피와 개발 없이 못 살아요 👩🏻‍💻</p>
					<p id="d83c5778-b01f-4b50-a93d-a130b87b4903" class="">
						<span class="mini-icon">
							<a href="https://github.com/Ting-Kim">
								<i class="fab fa-github" id="mini-icon"></i>
							</a>
						</span>
						<span class="mini-icon">
							<a href="https://ting-kim.github.io/"><i class="fas fa-blog" id="mini-icon"></i></a>
						</span>
						<span class="mini-icon">
							<a href="#" id="btn-email" class="btn btn-primary" data-toggle="popover" title="ting_916@naver.com" data-placement="bottom">
								<i class="fas fa-envelope" id="mini-icon"></i>
							</a>
						</span>
					</p>
					<p id="0effdb0a-4bd8-44c2-85da-3c3f9f035357" class=""></p>
				</div>
				<div id="1964993a-4eeb-4e15-9b3e-bf7bbb7cce5d" style="width:68.75%" class="column">
					<h2 id="faf79c7f-2b5c-43f2-9d64-8c51cf70f5ab" class="">안녕하세요. 개발자라는 꿈에 도전하고 있는 김태호입니다 !</h2>
					<p id="7fe42f70-21af-48a4-a709-d24a554c6411" class="">인생에서 가장 중요하게 생각하는게 
						<span style="background-color:#faf4c0;">성장</span>입니다 👊🏻<br>사람들과 만나고 많은 경험으로 부터 항상 많은 걸 배우고자 합니다.<br>커피를 사랑하며, 주량은 약하지만 맥주와 치킨을 좋아합니다 🍻<br>🦮🐕‍🦺강아지 2마리, 고양이🐈와 재미있게 살고 있습니다.</p>
					<p id="1d58009c-67c8-4ec8-a61a-d3b92e4ec3b3" class=""></p>
					<ul class="toggle">
						<li>
							<details close="">
								<summary><span style="color:gray; opacity: 0.5;">아이들 사진이 궁금해요!</span></summary>
								<figure class="image">
									<a href="#">
										<div><b>송아</b></div>
										<img style="width:192px" src="{% static 'eda/songa.jpg' %}"/>
									</a>
								</figure>
								<figure class="image">
									<a href="#">
										<div><b>몽아</b></div>
										<img style="width:192px" src="{% static 'eda/monga.jpg' %}"/>
									</a>
								</figure>
								<figure class="image">
									<a href="#">
										<div><b>엘리</b></div>
										<img style="width:192px" src="{% static 'eda/ally.jpg' %}"/>
									</a>
								</figure>
								<hr>
							</details>
						</li>
					</ul>
					<p id="07d54434-f7ae-462c-b2fc-fecdf06052b7" class=""></p>
					<p id="9993fca4-c0fe-4140-a95f-f3a51ec2eda5" class=""></p>
					<br>
					<br>
					<h2 id="cd4213a3-94f1-4a52-83ec-7ec12b46ef33" class="">다뤄 본 기술들</h2>
					<img src="{% static 'eda/sw_technique.PNG' %}">
					<p id="f88e8ab4-b44f-4370-bab4-8b398eec9210" class=""></p>
					<br>
					<br>
					<h2 id="f42a0b2a-cd6d-43f4-8150-4f7954f65541" class="">History</h2>
					<p id="ee5df8ae-8114-47d3-8483-4be11021e63d" class="">2013.03-2019.08  숭실대학교 기계공학과 졸업</p>
					<p id="36d96d51-037b-45c8-b0eb-ca07f4bda1a6" class="">2018.07-2018.09  현대건설 H-Contech 2기 해외기술봉사단(베트남)</p>
					<p id="093986fd-6ab8-4e68-8f9c-fe4e10d487ec" class="">2018.09-2018.12  LG전자 생산기술원 공정장비 인턴 근무</p>
					<p id="d431e66d-8cbc-4466-a883-cbd5a8f9fe30" class="">2019.06-2020.02  한국NSK 생산관리 근무</p>
					<p id="ff2ee303-154e-4cec-a493-a5976146ffd9" class="">2020.03-2020.08  쌍용교육센터 Java 기반 웹 개발 교육 수료</p>
					<p id="cd392954-3d06-4d12-aed1-ab74a8749c8f" class="">2020.10 2020.10  한국인터넷진흥원 핀테크 개발 교육 과정 수료(2주)</p>
					<p id="12b570ec-66e3-49fa-b79f-4ce1af7e9afd" class="">2020.12-진행 중   Programmers K-Digital 인공지능 데브 코스</p>
					<p id="5bd6ce50-7c70-4425-bfd3-504a15d2fde4" class=""></p>
					<p id="f8ccddd8-dbb4-4978-9768-a0a622112d07" class=""></p>
					<p id="907161b6-777a-4199-9aad-b282c57d85e9" class=""></p>
				</div>
			</div>
			<p id="9846d5ee-fd32-466e-bf81-bc4c13a58595" class=""></p>
			<p id="9f324c15-30a9-4f01-ae1b-c299e91a9d25" class=""></p>
		</div>
	</article>
	<script>
		(function() {
			$('[data-toggle="popover"]').popover();   
		})()
	</script>
</body>
</html>

myeda/eda/templates/eda/myeda.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>EDA project</title>
</head>
<body>
<p>Hello World</p>
{% autoescape off %}
<p>head(5)</p>
{{ head }}

<p>tail(5)</p>
{{ tail }}

{{ graph1 }}
{% endautoescape %}



</body>
</html>